version: '3.8'

services:
  betteraskcat-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./cards.json:/app/cards.json:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - betteraskcat-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  betteraskcat-network:
    driver: bridge 